#####################
### JEKYLL CONFIG ###
#####################
markdown: kramdown
highlighter: none

###############
### GENERAL ###
###############
domain: puppy-tools.github.io
url: https://puppy-tools.github.io
author: nik0-dev 
project-name: puppy-console

###################
### GITHUB INFO ###
###################
personal-github: https://github.com/nik0-dev
project-github: https://github.com/puppy-tools/puppy-console
website-github: https://github.com/puppy-tools/puppy-tools.github.io
